### ISSUE TITLE
使用 希沃白板 时写字会有延迟 且 触控时强制显示鼠标

### ISSUE THREAD

**Issue by got991** [RinLit-233-shiroko/Class-Widgets#102]
### 检查清单

- [x] 我已更新到最新版 ![GitHub Release](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_prereleases) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

1. 写字时没有延迟
2. 当使用触控时应不显示鼠标

### 实际结果

1. 写字时有大约 0.5s~1s 的延迟
2. 使用大屏幕触控时会强制显示鼠标

### 重现步骤

(1)
1. 启动
2. 打开希沃白板
3. 写字（可以感受到有明显延迟）
(2)
1. 启动
2. 随便使用大屏幕触控点一下空白处（强制显示鼠标）

### 应用版本

1.1.6.5

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

### 不要乱下载别人发的文件，特别是名字是fix.zip的文件。您是否遇见过这样的文件？

否

**Comment by got991** [comment]
没试过新版本（忘了有预发布了

**Comment by got991** [comment]
已测试，最新版本仍有此问题

**Comment by RinLit-233-shiroko** [comment]
请问能否提供更多详细信息（如录屏、任务管理器中 Class Widgets 的性能占用情况），目前在我的机器上并未发现此问题

**Comment by got991** [comment]
> 请问能否提供更多详细信息（如录屏、任务管理器中 Class Widgets 的性能占用情况），目前在我的机器上并未发现此问题

好的，等我下次回学校之后录一下

**Comment by got991** [comment]
> 请问能否提供更多详细信息（如录屏、任务管理器中 Class Widgets 的性能占用情况），目前在我的机器上并未发现此问题

目前无法复现

**Comment by RinLit-233-shiroko** [comment]
啊？又一个偶发性bug
