### ISSUE TITLE
奇怪的时间表问题

### ISSUE THREAD

**Issue by MKStoler4096** [RinLit-233-shiroko/Class-Widgets#112]
### 检查清单

- [X] 我已更新到最新版 ![GitHub Release](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_prereleases) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

正常显示。

### 实际结果

直接显示不出来任何一节课。

如果配置文件有误，能帮我改改吗，触控改起来太麻烦了（）

### 重现步骤

见图：
![2024-10-23_21-01-167d7e898c704747f59e71c10a154f788b](https://github.com/user-attachments/assets/b6df6703-8093-40e8-819b-c8a22f24e5f7)
以及json文件：
[新高二.json](https://github.com/user-attachments/files/17491727/default.json)

### 堆栈跟踪（可选）

```shell
无
```

### 应用版本

1.1.7-b3

### 操作系统版本

10.0.26100

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

### 不要乱下载别人发的文件，特别是名字是fix.zip的文件。您是否遇见过这样的文件？

是

**Comment by RinLit-233-shiroko** [comment]
![image](https://github.com/user-attachments/assets/33a37362-a0f8-4c53-b3ee-f54ff0f3b858)
您所指的“读取不出来”是什么意思呢，据此截图并未发现任何异常，能更加具体地描述吗？

**Comment by MKStoler4096** [comment]
哎？？？今天疑似好了？？？

先关了，看看有没有复现（）

**Comment by RinLit-233-shiroko** [comment]
找到问题了，是时间排序的问题，目前修好了

**Comment by MKStoler4096** [comment]
好滴，等我测一下，没问题就关了

**Comment by MKStoler4096** [comment]
ok，看起来没问题
