### ISSUE TITLE
时长组件缺失了一个圆角

### ISSUE THREAD

**Issue by MKStoler4096** [RinLit-233-shiroko/Class-Widgets#115]
### 检查清单

- [X] 我已更新到最新版 ![GitHub Release](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_prereleases) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

四角圆角

### 实际结果

时长组件缺失了一个圆角，请看右下角：
![image](https://github.com/user-attachments/assets/13f44f44-a914-4cf3-8968-c43d265a7668)

### 重现步骤

啥也没干

### 堆栈跟踪（可选）

```shell
无
```

### 应用版本

1.1.7-b3

### 操作系统版本

10.0.26100

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

### 不要乱下载别人发的文件，特别是名字是fix.zip的文件。您是否遇见过这样的文件？

是

**Comment by RinLit-233-shiroko** [comment]
其实是故意的 _((或者说懒得处理_

**Comment by RinLit-233-shiroko** [comment]
介意的话会改的

**Comment by MKStoler4096** [comment]
不介意（（（
*原来是有意为之吗*

**Comment by MKStoler4096** [comment]
豪德，其实这是图片大小多出来一块没裁剪……
