### ISSUE TITLE
每天18:00，课程表都会失效

### ISSUE THREAD

**Issue by herobrinein** [RinLit-233-shiroko/Class-Widgets#116]
### 检查清单

- [X] 我已更新到最新版 ![GitHub Release](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_prereleases) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

在18:00之后的课程进行正常显示和倒计时

### 实际结果

每到18:00时，所有的倒计时中断，课程表显示为暂无课程

https://github.com/user-attachments/assets/9ef1097b-1e51-4bb1-bc87-0b289bab6672

### 重现步骤

1.将时间调到17:59
2.等到18:00

### 应用版本

1.1.7-b3

### 操作系统版本

Windows 11 24H2 (OS内部版本 26100.1742

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

### 不要乱下载别人发的文件，特别是名字是fix.zip的文件。您是否遇见过这样的文件？

否

**Comment by RinLit-233-shiroko** [comment]
https://github.com/user-attachments/assets/9a93d41b-c02a-44aa-9100-23bc41a54484

能否给出您的课程表配置文件，目前未发现此异常。因为我怀疑和 #112 有关

**Comment by herobrinein** [comment]
[新课表 - 1.json](https://github.com/user-attachments/files/17513810/-.1.json)
这个是最初的配置文件，晚修的课程不显示，我把晚修课程并入下午，18：00又没了

**Comment by MKStoler4096** [comment]
测一下最新版Actions的生成版本。

**Comment by herobrinein** [comment]
> QQ20241024-175944.mp4 
> 能否给出您的课程表配置文件，目前未发现此异常。因为我怀疑和 #112 有关
这个是最初的配置文件，晚修的课程配置了但不显示，我把晚修课程并入下午，再进行测试才出现了以上的bug，18：00又没了
[-.1.json](https://github.com/user-attachments/files/17515823/-.1.json)

**Comment by herobrinein** [comment]
> 此配置文件经测试，在最新的提交中无问题。会在下个版本修复


所以是确实有bug，而不是配置文件的问题，对吧

**Comment by RinLit-233-shiroko** [comment]
> > 此配置文件经测试，在最新的提交中无问题。会在下个版本修复
> 
> 所以是确实有bug，而不是配置文件的问题，对吧

没错的

**Comment by herobrinein** [comment]
> > > 此配置文件经测试，在最新的提交中无问题。会在下个版本修复
> > 
> > 
> > 所以是确实有bug，而不是配置文件的问题，对吧
> 
> 没错的

[UP帮我看一下，这个配置文件在周六上午不显示是不是也属于此类bug？
[Uploading 新课表 - 1.json…]()

**Comment by RinLit-233-shiroko** [comment]
应该

> > > > 此配置文件经测试，在最新的提交中无问题。会在下个版本修复
> > > 
> > > 
> > > 所以是确实有bug，而不是配置文件的问题，对吧
> > 
> > 
> > 没错的
> 
> 开发者大大，能帮我看一下，这个配置文件在周六上午不显示是不是也属于此类bug？非常感谢 [新课表 - 1.json]
应该是的

**Comment by herobrinein** [comment]
ok非常感谢
