### ISSUE TITLE
每个时段最后一节课的最后25分钟会“暂无课程”

### ISSUE THREAD

**Issue by WRMYX** [RinLit-233-shiroko/Class-Widgets#121]
### 检查清单

- [X] 我已更新到最新版 ![GitHub Release](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_prereleases) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

正常的显示上下课时间

### 实际结果

每个时段的最后一节课的最后25分钟会“暂无课程”，时间表在这里！（https://www.123pan.com/s/iUrajv-ioH8v）

### 重现步骤

1.每天最后一个时段的最后一节课的最后25分钟

### 应用版本

1.1.7-b3

### 操作系统版本

23H2

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

### 不要乱下载别人发的文件，特别是名字是fix.zip的文件。您是否遇见过这样的文件？

否

**Comment by RinLit-233-shiroko** [comment]
目前在最新的提交库中暂未复现，可能Bug也是 #112 反馈的，目前已修复

**Comment by Yersmagit** [comment]
> @RinLit-233-shiroko 
> 目前在最新的提交库中暂未复现，可能Bug也是 #112 反馈的，目前已修复

**在最新版本 1.1.7-b3 中，问题依旧可以成功复现。**复现方法参见 #109

**Comment by RinLit-233-shiroko** [comment]
> > @RinLit-233-shiroko
> > 目前在最新的提交库中暂未复现，可能Bug也是 #112 反馈的，目前已修复
> 
> **在最新版本 1.1.7-b3 中，问题依旧可以成功复现。** 复现方法参见 #109

修复的还没打包发布

**Comment by Yersmagit** [comment]
> 修复的还没打包发布

抱歉没看 Actions 哈哈。话说我记得作者大大之前的使用习惯不是只有发布版本的时候才会上传 codes 嘛

**Comment by Yersmagit** [comment]
> @RinLit-233-shiroko
> 修复的还没打包发布

使用最新的库（未打包的 v1.1.7 - b4, commit: fdf1e05fbdab2e5b8af53e1ed60c3d24c9b50bdb）进行了测试，问题仍可复现。（如图）
![image](https://github.com/user-attachments/assets/1271dde8-af9f-44b1-92c5-53c4b9c31aef)
复现方式还是参见 #109。
上图中使用的课表文件：
[新课表 - 1.json](https://github.com/user-attachments/files/17609378/-.1.json)
```json
{
    "part": {
        "0": [
            12,
            21
        ],
        "1": [
            12,
            52
        ]
    },
    "part_name": {
        "0": "上午",
        "1": "下午"
    },
    "timeline": {
        "default": {
            "a01": "31",
            "a11": "31"
        },
        "0": {},
        "1": {},
        "2": {},
        "3": {},
        "4": {},
        "5": {},
        "6": {}
    },
    "schedule": {
        "0": [
            "未添加",
            "未添加"
        ],
        "1": [
            "未添加",
            "未添加"
        ],
        "2": [
            "未添加",
            "未添加"
        ],
        "3": [
            "未添加",
            "未添加"
        ],
        "4": [
            "未添加",
            "未添加"
        ],
        "5": [
            "科技",
            "未添加"
        ],
        "6": [
            "科技",
            "未添加"
        ]
    },
    "schedule_even": {
        "0": [
            "未添加",
            "未添加"
        ],
        "1": [
            "未添加",
            "未添加"
        ],
        "2": [
            "未添加",
            "未添加"
        ],
        "3": [
            "未添加",
            "未添加"
        ],
        "4": [
            "未添加",
            "未添加"
        ],
        "5": [
            "科技",
            "未添加"
        ],
        "6": [
            "科技",
            "音乐"
        ]
    }
}
```

**Comment by RinLit-233-shiroko** [comment]
已在 abad94c 中更改获取节点的逻辑，已修复。
