### ISSUE TITLE
小浮窗在上课不能正常弹出和出现遮挡问题

### ISSUE THREAD

**Issue by WRMYX** [RinLit-233-shiroko/Class-Widgets#122]
### 检查清单

- [X] 我已更新到最新版 ![GitHub Release](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_prereleases) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

小浮窗在上课正常弹出，不会出现遮挡问题

### 实际结果

小浮窗在上课不能正常弹出和出现遮挡问题
![屏幕截图 2024-10-24 182014](https://github.com/user-attachments/assets/bba7b5c0-8253-4449-ac69-eec00cbe93de)
![屏幕截图 2024-10-23 183658](https://github.com/user-attachments/assets/9566a86f-379a-4d54-836e-73d1dcba6654)

### 重现步骤

1.把小浮窗设置成上课自动隐藏

### 应用版本

1.1.7-b3

### 操作系统版本

23H2

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

### 不要乱下载别人发的文件，特别是名字是fix.zip的文件。您是否遇见过这样的文件？

否

**Comment by WRMYX** [comment]
不知道是不是分辨率的问题

**Comment by herobrinein** [comment]
我有时也会出现这种情况，但我重新折叠又好了

**Comment by WRMYX** [comment]
> 我有时也会出现这种情况，但我重新折叠又好了

不，我们这里他折叠后还是这样

**Comment by RinLit-233-shiroko** [comment]
如果关掉“自动隐藏”功能，正常点击使其缩放是正常的吗

**Comment by RinLit-233-shiroko** [comment]
测试了一下，似乎跟 #111 有关，已做修复
