### ISSUE TITLE
课程数量问题

### ISSUE THREAD

**Issue by 1235612356** [RinLit-233-shiroko/Class-Widgets#13]
课程数大于等于8时，对第9节课及以后的课程表编辑功能异常；
课程数大于等于10时，在时间线中添加新的课程并保存会导致闪退。

**Comment by RinLit-233-shiroko** [comment]
请问能更详细描述此 Bug 吗

**Comment by 1235612356** [comment]
https://github.com/user-attachments/assets/6d429b87-4d93-41a9-9539-1ec1c2576f93

https://github.com/user-attachments/assets/8e5689ed-dd40-41d9-a082-284980446b9a

**Comment by RinLit-233-shiroko** [comment]
两项 Bug （课程表显示错误&读取闪退）均已修复，将在下个版本更新。
