### ISSUE TITLE
添加时间线卡死

### ISSUE THREAD

**Issue by liwezee** [RinLit-233-shiroko/Class-Widgets#14]
我在添加时间线的时候保存课程表会卡死，无法退出软件，任务管理器也无法结束进程，而且强制重启电脑之后课程表会无法打开，要删了重新解压才行，目前是偶发的，我保存了5次会有2次这样，第二次卡死等了几分钟就闪退了，而且也是闪退之后就不能再打开了

**Comment by RinLit-233-shiroko** [comment]
现在已经解决问题了，会在下个版本解决此问题
