### ISSUE TITLE
铃声提醒功能疑似失效

### ISSUE THREAD

**Issue by Leozhu2010** [RinLit-233-shiroko/Class-Widgets#141]
### 检查清单

- [X] 我已更新到最新版 ![GitHub Release](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_prereleases) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

正常来说，在开启提醒功能之后，上下课应该有弹窗提醒

### 实际结果

顾名思义，弹窗提醒失效了
进到设置发现所有提醒选项全部被关闭
开启之后提醒同样无效，过段时间又自己关闭了

### 重现步骤

使用11.1.7-b3版本

### 应用版本

1.1.7-b3

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by Leozhu2010** [comment]
如可以，请速修复！！已经严重影响了软件的关键功能之一

**Comment by Leozhu2010** [comment]
（玄学问题，可能概率复现，如有需要我可以在周二考完期中之后提供出问题的课表跟config文件）

**Comment by xuanxuan1231** [comment]
我这里还没出现问题，可能和课表有关（？

**Comment by Leozhu2010** [comment]
好，我晚上去拷下课表看看；
同时准备更新还没打包的1.1.7-b4

**Comment by MKStoler4096** [comment]
看看有给cw文件读写权限吗

**Comment by Leozhu2010** [comment]
给了，之前版本都没问题的
目前更新到1.1.7-b4之后问题神奇的消失了
我稍后传上来1.1.7-b3出问题的config跟课表
[General]
schedule = 新课表-1.json
pin_on_top = 1
margin = 10
time_offset = 30
opacity = 95
auto_startup = 0
hide = 0
hide_method = 2
full_hide = 0
color_mode = 2
enable_toast = 1
enable_alt_schedule = 1
blur_countdown = 0
theme = default

[Toast]
wave = 1
pin_on_top = 1
ringtone = 1
prepare_minutes = 2

[Weather]
city = 440606
api = amap_weather
api_key = 9f9a23db9e204659c55c38433b8e907a

[Color]
attend_class = DD986F
finish_class = 61C88E
prepare_class = #7065D8

[Date]
start_date = 2024-9-2
cd_text_custom = 期中考试
countdown_date = 2024-11-3

[Audio]
volume = 75
attend_class = attend_class.wav
finish_class = finish_class.wav
prepare_class = prepare_class.wav

[Temp]
set_week = 
temp_schedule = 

[Other]
do_not_log = 0
initialstartup = 
multiple_programs = 0
version = 1.1.7-b3
[新课表-1.json](https://github.com/user-attachments/files/17645452/-1.json)

**Comment by Yersmagit** [comment]
1.1.7-b4 还是有问题，可以概率复现
