### ISSUE TITLE
时间线中的活动在拖拽调整先后顺序后 无法将更改应用

### ISSUE THREAD

**Issue by Yersmagit** [RinLit-233-shiroko/Class-Widgets#143]
### 检查清单

- [X] 我已更新到最新版 ![GitHub Release](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_prereleases) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

时间线中的活动通过拖拽调整排序后，可以如 `v1.1.6.5` 一样，正常保存更改

### 实际结果

时间线中的活动通过拖拽调整排序后，点击“保存”，程序不会对课程表文件作任何更改。也就是说，实际上，用户无法在程序内调整课程表活动的排序。

_此问题可在_ `v1.1.7-b1` _及其以后的版本中复现。_

### 重现步骤

1. 新建一个空白课表（或者是已有的课表
2. 在时间线编辑页面中添加几个活动（包括课程与课间
3. 随便点不点保存都行
4. 拖拽调整时间线的排序（随便咋拖都行
5. 点击保存后，程序只会将第 4 步前的时间线信息保存在 json 文件中

### 应用版本

1.1.7-b4 _(未打包_

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by xuanxuan1231** [comment]
已经交pr了 等merge发件人: ***@***.*** ***@***.***> 代表 Yersmagit ***@***.***>发送时间: 星期六, 十一月 9, 2024 6:56:34 下午收件人: Class-Widgets ***@***.***>抄送: subscribed ***@***.***>主题: [RinLit-233-shiroko/Class-Widgets] 时间线中的活动在拖拽调整先后顺序后 无法将更改应用 (Issue #143)
检查清单

 我已更新到最新版  ，并看过最新提交，确认这一 Bug 还没有修复。
 我已在 Issues 中检索，确认这一 Bug 未被提交过。
 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

期望的行为
时间线中的活动通过拖拽调整排序后，可以如 v1.1.6.5 一样，正常保存更改
实际结果
时间线中的活动通过拖拽调整排序后，点击“保存”，程序不会对课程表文件作任何更改。也就是说，实际上，用户无法在程序内调整课程表活动的排序。
此问题可在 v1.1.7-b1 及其以后的版本中复现。
重现步骤
新建一个空白课表（或者是已有的课表在时间线编辑页面中添加几个活动（包括课程与课间随便点不点保存都行拖拽调整时间线的排序点击保存后，程序只会将第 4 步前的时间线信息保存在 json 文件中
堆栈跟踪（可选）
No response
应用版本
1.1.7-b4 （未打包
操作系统版本
No response
最后一步

 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by xuanxuan1231** [comment]
已经交pr了 等merge

**Comment by Yersmagit** [comment]
> 已经交pr了 等合并

已经看到力\^o^/
