### ISSUE TITLE
可以无限制的打开“额外功能”窗口

### ISSUE THREAD

**Issue by MKStoler4096** [RinLit-233-shiroko/Class-Widgets#16]
没有检测窗口是否在运行中，只要不停点击当前活动就能触发这个问题。
而且主窗体也没有多开检测
![image](https://github.com/user-attachments/assets/29ac672e-dd2e-4e9a-89a7-bcbec4a04f39)

**Comment by ZianTT** [comment]
that may be a feature rather than a bug?

**Comment by RinLit-233-shiroko** [comment]
防多开已经做好力，将在下个版本更新

**Comment by MKStoler4096** [comment]
好嘞
