### ISSUE TITLE
希望提供为一周的每一天设置独立的时间线的功能

### ISSUE THREAD

**Issue by mdogwoop** [RinLit-233-shiroko/Class-Widgets#21]
我校在周一到周五和周日这两个不同日期使用不同的时间线，所以希望可以增加为一周内的每一天提供不同时间线的功能

**Comment by Leozhu2010** [comment]
确实需要，毕竟我们周五没有晚修周六周日不上课

**Comment by RinLit-233-shiroko** [comment]
已在v1.1.7-b1中实现，详见https://www.yuque.com/rinlit/class-widgets_help/swg86btkivirtnrl
