### ISSUE TITLE
未出现课表

### ISSUE THREAD

**Issue by Shotazt** [RinLit-233-shiroko/Class-Widgets#28]
### 检查清单

- [X] 我已更新到最新版 ![GitHub Release](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_prereleases) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

希望出现课表，大佬这是为什么会出现这种状况

### 实际结果

课表并未出现
<img width="960" alt="屏幕截图 2024-09-02 170435" src="https://github.com/user-attachments/assets/7d659bfc-27b9-4004-93cb-deff3fcdf92b">
<img width="960" alt="屏幕截图 2024-09-02 170610" src="https://github.com/user-attachments/assets/eec8278a-ea0a-450c-8ef7-0462aa97af09">

### 重现步骤

正常操作

### 应用版本

1.1.1.5

### 操作系统版本

Win11

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

### 不要乱下载别人发的文件，特别是名字是fix.zip的文件。您是否遇见过这样的文件？

是

**Comment by Shotazt** [comment]
时间线也正常填写却不能使用
<img width="960" alt="屏幕截图 2024-09-02 183650" src="https://github.com/user-attachments/assets/e9e6668f-d7ba-4acb-8d66-d589fb5cd700">

**Comment by ZianTT** [comment]
需要在课程设置中正确添加当日课程

**Comment by Shotazt** [comment]
> 需要在课程设置中正确添加当日课程

大佬能说详细一点吗，我比较笨，不太清楚怎么搞
<img width="960" alt="屏幕截图 2024-09-02 223258" src="https://github.com/user-attachments/assets/5097f8c4-725b-4c7d-a01b-5368a43a8cdd">

**Comment by ZianTT** [comment]
> > 需要在课程设置中正确添加当日课程
> 
> 大佬能说详细一点吗，我比较笨，不太清楚怎么搞
> <img width="960" alt="屏幕截图 2024-09-02 223258" src="https://github.com/user-attachments/assets/5097f8c4-725b-4c7d-a01b-5368a43a8cdd">
> 

左侧课程表编辑

**Comment by ZianTT** [comment]
> > 需要在课程设置中正确添加当日课程
> 
> 大佬能说详细一点吗，我比较笨，不太清楚怎么搞
> <img width="960" alt="屏幕截图 2024-09-02 223258" src="https://github.com/user-attachments/assets/5097f8c4-725b-4c7d-a01b-5368a43a8cdd">
> 

能看一下时间线和课程表截图吗，可能是时间配置出错了

**Comment by Shotazt** [comment]
> > > 需要在课程设置中正确添加当日课程
> > 
> > 
> > 大佬能说详细一点吗，我比较笨，不太清楚怎么搞
> > <img alt="屏幕截图 2024-09-02 223258" width="960" src="https://private-user-images.githubusercontent.com/149293521/363724559-5097f8c4-725b-4c7d-a01b-5368a43a8cdd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMzE1OTksIm5iZiI6MTcyNTMzMTI5OSwicGF0aCI6Ii8xNDkyOTM1MjEvMzYzNzI0NTU5LTUwOTdmOGM0LTcyNWItNGM3ZC1hMDFiLTUzNjhhNDNhOGNkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwM1QwMjQxMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZDM1NmJkMjAzMzNhNTEwYWJiZmJlNGUzZWMxZTlmYmRhOTYzZDc1MjA5NWU3M2FiMzdiMTk5MGU1Y2ZiZWRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iTHeSA6Kqw7RJb_sHx3kolq1qxv_subL0xFNgLk_-LQ">
> 
> 能看一下时间线和课程表截图吗，可能是时间配置出错了

<img width="960" alt="屏幕截图 2024-09-03 095055" src="https://github.com/user-attachments/assets/7a9660fb-3bcf-4489-a6c3-1d1aec16887a">
<img width="960" alt="屏幕截图 2024-09-03 095113" src="https://github.com/user-attachments/assets/dec4c60c-def4-40b8-8c6b-5e8c8d76882e">
<img width="960" alt="屏幕截图 2024-09-03 095136" src="https://github.com/user-attachments/assets/b0e903a7-6091-4242-9609-725b1661c6e0">
<img width="960" alt="屏幕截图 2024-09-03 095156" src="https://github.com/user-attachments/assets/3aba5ccb-eca4-487f-b32d-514952f6ecdd">
[新课表 - 1.json](https://github.com/user-attachments/files/16842839/-.1.json)
谢谢大佬

**Comment by RinLit-233-shiroko** [comment]
重新发送一下配置文件，https://github.com/user-attachments/files/16842839/-.1.json这个网址失效了

**Comment by Shotazt** [comment]
> 重新发送一下配置文件，[https://github.com/user-attachments/files/16842839/-.1.json这个网址失效了](https://github.com/user-attachments/files/16842839/-.1.json%E8%BF%99%E4%B8%AA%E7%BD%91%E5%9D%80%E5%A4%B1%E6%95%88%E4%BA%86)




> 重新发送一下配置文件，[https://github.com/user-attachments/files/16842839/-.1.json这个网址失效了](https://github.com/user-attachments/files/16842839/-.1.json%E8%BF%99%E4%B8%AA%E7%BD%91%E5%9D%80%E5%A4%B1%E6%95%88%E4%BA%86)

[新课表 - 1.txt](https://github.com/user-attachments/files/16846112/-.1.txt)

**Comment by Shotazt** [comment]
> > > 重新发送一下配置文件，[https://github.com/user-attachments/files/16842839/-.1.json这个网址失效了](https://github.com/user-attachments/files/16842839/-.1.json%E8%BF%99%E4%B8%AA%E7%BD%91%E5%9D%80%E5%A4%B1%E6%95%88%E4%BA%86)
> > 
> > 
> > > 重新发送一下配置文件，[https://github.com/user-attachments/files/16842839/-.1.json这个网址失效了](https://github.com/user-attachments/files/16842839/-.1.json%E8%BF%99%E4%B8%AA%E7%BD%91%E5%9D%80%E5%A4%B1%E6%95%88%E4%BA%86)
> > 
> > 
> > [新课表 - 1.txt](https://github.com/user-attachments/files/16846112/-.1.txt)
> 
> 把json格式改成txt就好上传了，由于在学校，所以回的比较慢

[config.zip](https://github.com/user-attachments/files/16846869/config.zip)

**Comment by RinLit-233-shiroko** [comment]
等一下，这个程序的时间是使用24小时制的，你在下午的课程填2:15不行，应改成14:15

**Comment by Shotazt** [comment]
> 等一下，这个程序的时间是使用24小时制的，你在下午的课程填2:15不行，应改成14:15

谢谢大佬，那请问这样子改明天桌面课程就能显示出来了吗，之前桌面课程都不会显示当前课程和接下来课程

**Comment by Shotazt** [comment]
> 等一下，这个程序的时间是使用24小时制的，你在下午的课程填2:15不行，应改成14:15

可以了，谢谢大佬耐心解答

**Comment by Shotazt** [comment]
已解决
