### ISSUE TITLE
临时换课时多次保存会覆盖原始课表

### ISSUE THREAD

**Issue by alexliu07** [RinLit-233-shiroko/Class-Widgets#30]
### 检查清单

- [X] 我已更新到最新版 ![GitHub Release](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_prereleases) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

在临时换课页面，可以临时替换当天课程，同时在重启程序的时候恢复原课表
当换课后只点击一次保存可以正常实现这个效果

### 实际结果

![image](https://github.com/user-attachments/assets/86b2a870-70f3-4d01-a4d9-0648b762e424)
多次单击保存后，发现用于备份原课表的config\schedule\backup.json被覆盖为换课后的课表，同时原课表会被覆盖，应该是存储临时课表的逻辑问题
在重新启动程序后，程序会无法启动，或者启动之后在课程表编辑界面崩溃

### 重现步骤

1. 在程序中添加一些课程 示例：
![image](https://github.com/user-attachments/assets/b1fc91db-86fc-4bc1-a7e9-328e75769451)
此时的config\schedule\新课表 - 1.json：[新课表 - 1.json](https://github.com/user-attachments/files/16839064/-.1.json)
2. 单击Widget中的 **当前活动** 打开 **更多功能 - 额外选项** 页面
3. 更换一节课程 以将周一的第二节“数学”更改为“音乐”为例：
![image](https://github.com/user-attachments/assets/94d6a6a4-0ee1-41a4-88ee-35db1998e56a)
4. 单击一次 **保存**，会发现程序自动将原有课表备份到config\schedule\backup.json
此时的config\schedule\新课表 - 1.json：[新课表 - 1.json](https://github.com/user-attachments/files/16839069/-.1.json)
此时的config\schedule\backup.json：[backup.json](https://github.com/user-attachments/files/16839085/backup.json)
6. 继续单击 **保存**，会发现程序将临时课表保存到config\schedule\backup.json里面，覆盖了原来的课表
此时的config\schedule\新课表 - 1.json：[新课表 - 1.json](https://github.com/user-attachments/files/16839087/-.1.json)
此时的config\schedule\backup.json：[backup.json](https://github.com/user-attachments/files/16839091/backup.json)
8. 重启软件，发现课程表中只剩下了刚才临时换课之后的周一课程
![image](https://github.com/user-attachments/assets/0ee06e93-87a3-4b3c-aa68-44488cf55e21)
9. 在 **课程表编辑** 页面的 **选择星期** 中选择其他星期，程序崩溃

### 堆栈跟踪（可选）

```shell
log文件夹中的所有日志均只有INFO级别的信息
没有ERROR或WARN
都是类似这样的信息：
2024-09-02 22:52:19.078 | INFO     | __main__:<module>:525 - 显示窗口：Form
2024-09-02 22:52:23.130 | INFO     | __main__:open_settings:356 - 打开“设置”
2024-09-02 22:58:57.812 | INFO     | menu:se_upload_list:497 - 更新列表：课程表编辑
```

### 应用版本

1.1.5.5

### 操作系统版本

10.0.22631.4112

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

### 不要乱下载别人发的文件，特别是名字是fix.zip的文件。您是否遇见过这样的文件？

否

**Comment by RinLit-233-shiroko** [comment]
现在已经加上检查机制了，会在下个版本更新修复此Bug
