### ISSUE TITLE
4k屏在高缩放时打开换课表时，会显示到屏幕外面

### ISSUE THREAD

**Issue by mifeixiong** [RinLit-233-shiroko/Class-Widgets#31]
### 检查清单

- [X] 我已更新到最新版 ![GitHub Release](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_prereleases) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

希望修一下

### 实际结果

换课表完全在屏幕外边

### 重现步骤

屏幕分辨率为3840x2160
缩放开到了300%
点击上方的活动

### 应用版本

1.1.5.5

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

### 不要乱下载别人发的文件，特别是名字是fix.zip的文件。您是否遇见过这样的文件？

否

**Comment by xuanxuan1231** [comment]
连点两下标题栏最大化，可以当做临时解决办法

**Comment by mifeixiong** [comment]
> 连点两下标题栏最大化，可以当做临时解决办法

主要是看不到标题栏啊（

**Comment by xuanxuan1231** [comment]
> > 连点两下标题栏最大化，可以当做临时解决办法
> 
> 主要是看不到标题栏啊（

我想起来了，或者从任务管理器最大化？

**Comment by xuanxuan1231** [comment]
> > 连点两下标题栏最大化，可以当做临时解决办法
> 
> 主要是看不到标题栏啊（

我想起来了，或者从任务管理器最大化？

**Comment by RinLit-233-shiroko** [comment]
已修复该问题，将在下个版本更新
