### ISSUE TITLE
支持晚自习时段 / 自定义时段

### ISSUE THREAD

**Issue by Pigeon0v0** [RinLit-233-shiroko/Class-Widgets#32]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_releases&style=flat-square&label=) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认我想要的功能还没有实现。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我认为我想要的功能是用户广泛需要的，插件不能替代的，且没有超出 **软件本来** 的开发目标，而非 **添加与课表及教学辅助无关的内容** 。
- [X] 我已知晓由于开发者时间精力有限，我提交的功能请求可能需要比较久的时间才能实现。

### 背景与动机

由于目前固定了上午和下午两个时段，对于有晚自习的学校来说，晚自习时间的课表必须顺着下午的时间排下来，不太方便

### 想要实现或优化的功能

如题，支持增加单独的晚自习时段，如果可以做成自定义时段就更好了

### 最后一步

- [X] 我认为上述的描述已经足以详细，以便开发人员理解您想要的功能。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

### 不要乱下载别人发的文件，特别是名字是fix.zip的文件。您是否遇见过这样的文件？

否

**Comment by RinLit-233-shiroko** [comment]
已在v1.1.7-b1中实现，详见：https://www.yuque.com/rinlit/class-widgets_help/swg86btkivirtnrl
