### ISSUE TITLE
支持在上课提醒框中显示本节课课程名称

### ISSUE THREAD

**Issue by Pigeon0v0** [RinLit-233-shiroko/Class-Widgets#33]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_releases&style=flat-square&label=) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认我想要的功能还没有实现。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我认为我想要的功能是用户广泛需要的，插件不能替代的，且没有超出 **软件本来** 的开发目标，而非 **添加与课表及教学辅助无关的内容** 。
- [X] 我已知晓由于开发者时间精力有限，我提交的功能请求可能需要比较久的时间才能实现。

### 背景与动机

有些时候小组件出于某些用户原因，不会开启置顶小组件，此时可能无法及时了解本节课信息。

### 想要实现或优化的功能

支持在原有的上课提醒框中显示本节课名称，以及当前时间等。

在 #32 的基础上，如果有两个上课时段连排（比如一整节晚自习分三段给三门课），最好可以显示如「数学 → 英语」这样的信息。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以便开发人员理解您想要的功能。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

### 不要乱下载别人发的文件，特别是名字是fix.zip的文件。您是否遇见过这样的文件？

否

**Comment by RinLit-233-shiroko** [comment]
加上啦
对了这里面提到的“以及当前时间等”具体是什么效果呢，希望能详细描述下

**Comment by Pigeon0v0** [comment]
就是在弹窗里还可以显示精确到秒的时间信息...

**Comment by RinLit-233-shiroko** [comment]
还是不太理解…抱歉
是指如下效果吗：
[ 上课  当前时间 23:33:33 当前课程 xxx ]

**Comment by Pigeon0v0** [comment]
> [ 上课  当前时间 23:33:33 当前课程 xxx ]

Ahh 是这样的
