### ISSUE TITLE
时间偏移在组件上不生效

### ISSUE THREAD

**Issue by DarkModest** [RinLit-233-shiroko/Class-Widgets#35]
### 检查清单

- [X] 我已更新到最新版 ![GitHub Release](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_prereleases) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

例如：
原定在北京时间 9:00:15 切换活动。此时系统时间应为北京时间 9:00:00。
因此，设置时间偏移量为15秒。
期望：在北京时间 9:00:15 时，切换活动。

### 实际结果

调整时间偏移量后，`widget-next-activity.ui` 并没有时间偏移。
系统时间到 9:00:00 时，`widget-next-activity.ui` 触发了活动切换；系统时间 9:00:15 时，下课提醒触发。

### 重现步骤

1. 设置时间线。在时间偏移量为0的情况下，能在 9:00:00 切换活动。
2. 设置时间偏移量为任意非零整数。

### 应用版本

v1.1.5.5

### 操作系统版本

Windows 10 on SEEWO

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

### 不要乱下载别人发的文件，特别是名字是fix.zip的文件。您是否遇见过这样的文件？

否

**Comment by RinLit-233-shiroko** [comment]
已修复该问题，将在下个版本发布解决
