### ISSUE TITLE
希望提供github打包exe的工作流

### ISSUE THREAD

**Issue by iGhx-me** [RinLit-233-shiroko/Class-Widgets#36]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_releases&style=flat-square&label=) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认我想要的功能还没有实现。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我认为我想要的功能是用户广泛需要的，插件不能替代的，且没有超出 **软件本来** 的开发目标，而非 **添加与课表及教学辅助无关的内容** 。
- [X] 我已知晓由于开发者时间精力有限，我提交的功能请求可能需要比较久的时间才能实现。

### 背景与动机

windows7无法正常打包exe目录

### 想要实现或优化的功能

希望提供github打包exe的工作流文件.yml,十分感谢

### 最后一步

- [X] 我认为上述的描述已经足以详细，以便开发人员理解您想要的功能。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

### 不要乱下载别人发的文件，特别是名字是fix.zip的文件。您是否遇见过这样的文件？

否

**Comment by ZianTT** [comment]
您需要自行填写version.txt文件后使用package文件下的pyinstaller命令进行打包

**Comment by iGhx-me** [comment]
ok

**Comment by iGhx-me** [comment]
可以出一期教程吗？谢谢

**Comment by DarkModest** [comment]
> 您需要自行填写version.txt文件后使用package文件下的pyinstaller命令进行打包

您好。可以具体描述打包过程吗？

**Comment by pizeroLOL** [comment]
> > 您需要自行填写version.txt文件后使用package文件下的pyinstaller命令进行打包
> 
> 您好。可以具体描述打包过程吗？

```powershell
# 准备环境
python -m venv venv
venv\Scripts\activate
pip install -r .\requirements.txt
pip install requests # 作者最新版把 requests 忘了
pip install pyinstaller # 打包工具

# 打包
pyinstaller main.py -w -i .\img\favicon.ico -n Class-Widgets

# 复制依赖文件
cp .\config\ .\dist\Class-Widgets\ -re
cp .\ui\ .\dist\Class-Widgets\ -re
cp .\img\ .\dist\Class-Widgets\ -re
cp .\audio .\dist\Class-Widgets\ -re
cp *.ui .\dist\Class-Widgets\
```
