### ISSUE TITLE
无课间的连续课程时的程序Bug

### ISSUE THREAD

**Issue by QYlyj** [RinLit-233-shiroko/Class-Widgets#37]
### 检查清单

- [X] 我已更新到最新版 ![GitHub Release](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_prereleases) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

当到达乙课程时间时，Class Widgets提示上课或无提示，随后直接正常进行乙课程的上课计时

### 实际结果

当到达乙课程时间时，Class Widgets提示下课，但随后正常进行乙课程的上课计时

### 重现步骤

设置甲乙两节无课间的连续课程，如下午的午读和第一节课

### 应用版本

1.1.5.5

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

### 不要乱下载别人发的文件，特别是名字是fix.zip的文件。您是否遇见过这样的文件？

否

**Comment by RinLit-233-shiroko** [comment]
已修复！
将在下个版本更新
