### ISSUE TITLE
换课时只能对单周课程操作

### ISSUE THREAD

**Issue by xuanxuan1231** [RinLit-233-shiroko/Class-Widgets#39]
### 检查清单

- [X] 我已更新到最新版 ![GitHub Release](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_prereleases) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

单周时换课换单周，双周时换课**换双周**

### 实际结果

单周时换课换单周，双周时换课**还是换单周**

### 重现步骤

1. 使用单双周添加课程
2. 将系统时间调到双周
3. 换课
4. 此时发现只换了单周课程(`schedule`)，双周课程(`schedule_even`)保持不变。顶部显示也是如此
5. 将系统时间调到单周
6. 顶部显示改变

### 应用版本

1.1.5.5

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

### 不要乱下载别人发的文件，特别是名字是fix.zip的文件。您是否遇见过这样的文件？

否

**Comment by RinLit-233-shiroko** [comment]
修复啦ヾ(≧▽≦*)o
将在下个版本更新
