### ISSUE TITLE
[Bug] 课程表对应错误

### ISSUE THREAD

**Issue by ZianTT** [RinLit-233-shiroko/Class-Widgets#4]
在timeline编辑中，若同时添加n（2个及以上）个课程（无课间）在schedule内默认仅计算n-1门课程

**Comment by RinLit-233-shiroko** [comment]
感谢反馈。
在此软件中每节课的空隙（上、下午的空隙不需要）需要添加课间及相应时长告诉软件，目前来说我没有比较好的解决方案。（配置文件的编写），所以一开始写的时候没在意，不过我会尝试解决这个问题的。

**Comment by hello8693DSZ** [comment]
可以参考我们[ClassIsland](https://github.com/ClassIsland/ClassIsland)档案文件编辑界面。

**Comment by RinLit-233-shiroko** [comment]
好了，修好力，现在源码传好了
