### ISSUE TITLE
win7可以使用吗

### ISSUE THREAD

**Issue by gwjcfls** [RinLit-233-shiroko/Class-Widgets#44]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_releases&style=flat-square&label=) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认我想要的功能还没有实现。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我认为我想要的功能是用户广泛需要的，插件不能替代的，且没有超出 **软件本来** 的开发目标，而非 **添加与课表及教学辅助无关的内容** 。
- [X] 我已知晓由于开发者时间精力有限，我提交的功能请求可能需要比较久的时间才能实现。

### 背景与动机

win7白板需要使用

### 想要实现或优化的功能

win7白班需要使用

### 最后一步

- [X] 我认为上述的描述已经足以详细，以便开发人员理解您想要的功能。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

### 不要乱下载别人发的文件，特别是名字是fix.zip的文件。您是否遇见过这样的文件？

否

**Comment by MKStoler4096** [comment]
我看没问题（）

**Comment by xuanxuan1231** [comment]
……建议升到10或11，要不然UI会**比较**割裂

**Comment by fred913** [comment]
@MKStoler4096 main.py 上月有一个commit加入了 match 语句，match 是在 Python 3.10 中加入的，Python 3.10 不兼容 Win7。我正好在尝试写 CI 脚本，会尝试将其替换为兼容 Python 3.8.10 的语法。稍后更新状态

**Comment by fred913** [comment]
> @MKStoler4096 main.py 上月有一个commit加入了 match 语句，match 是在 Python 3.10 中加入的，Python 3.10 不兼容 Win7。我正好在尝试写 CI 脚本，会尝试将其替换为兼容 Python 3.8.10 的语法。稍后更新状态

修改 match 语句后使用 `act` 编译成功，等 GitHub Actions 成功一次我就 PR 了。

**Comment by gwjcfls** [comment]
可以提供一下win7的版本吗？ 找不到呢😂

**Comment by fred913** [comment]
@gwjcfls 你可以在 GitHub Actions 下载最新的构建进行测试。Actions 的构建基于 Python 3.8.10，应该是兼容 Windows 7 的。

**Comment by fred913** [comment]
[GitHub Actions page](https://github.com/RinLit-233-shiroko/Class-Widgets/actions)

**Comment by gwjcfls** [comment]
十分感谢您😄

**Comment by gwjcfls** [comment]
当我尝试用win7运行时，先显示一下错误
Traceback (most recent call last):
  File "PyInstaller\loader\pyiboot01_bootstrap.py", line 83, in <module>
  File "PyInstaller\loader\pyimod04_pywin32.py", line 47, in install
  File "os.py", line 1109, in add_dll_directory
OSError: [WinError 127] 找不到指定的程序。: 'C:\\Users\\Administrator\\Desktop\\Windows-amd64\\_internal\\pywin32_system32'
然后我为电脑安装了KB2533623 补丁
而报错变为了
Traceback (most recent call last):
  File "main.py", line 3, in <module>
ImportError: DLL load failed while importing QtWidgets: 找不到指定的程序。

请大佬解决一下呢

**Comment by gwjcfls** [comment]
多谢大佬了，辛苦了，学校白板要用

**Comment by fred913** [comment]
如果你比较急的话可以直接加我qq，我通过email发你，有新进展直接联系

gwjcfls ***@***.***>于2024年10月1日 周二22:36写道：

**Comment by fred913** [comment]
1175882937，直接加我好了，修完电脑就开始测试，加好我就把qq号edit掉

sheng fan ***@***.***>于2024年10月1日 周二22:37写道：

**Comment by fred913** [comment]
@gwjcfls [Schedo](https://github.com/fred913/Schedo) 已测试基本兼容 Windows 7 环境。
