### ISSUE TITLE
软件1.1.5.5和1.1.6，在每天下午启动一体机时经常提示“读取配置文件时出错“

### ISSUE THREAD

**Issue by Leozhu2010** [RinLit-233-shiroko/Class-Widgets#45]
### 检查清单

- [X] 我已更新到最新版 ![GitHub Release](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_prereleases) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

我已将本软件实装至班级希沃一体机，ops型号MT71，正常来说，设置了开机自启动以后是应该自动启动并显示课表的（如本栏附
件日志所示）
[ClassWidgets_main_2024-09-14_13-57-50_986783.log](https://github.com/user-attachments/files/17002589/ClassWidgets_main_2024-09-14_13-57-50_986783.log)

### 实际结果

实际上，在每天下午开机的时候（早上一般可以正常启动），开机完毕了但是软件并未启动（准确来说，启动之后立刻崩溃），并且日志显示了以下两种错误（如本栏日志所示，我已经正确配置软件并设置好课表）
下附：出问题时候的配置文件、日志（分两种错误，本issue只提交第二种）（github不支持提交ini，所以config.ini变成了config.txt）
[config.txt](https://github.com/user-attachments/files/17002605/config.txt)

### 重现步骤

直接在下午两点左右正常开机一般就可以在班上一体机触发
可以通过重新安装软件（用压缩包里面的内容全部替换掉）解决，但是第二天下午开机时又会触发

### 堆栈跟踪（可选）

```shell
2024-09-14 13:54:18.120 | ERROR    | conf:write_conf:80 - 读取配置文件时出错: While reading from 'config.ini' [line 23]: section 'Temp' already exists
2024-09-14 13:54:18.121 | ERROR    | conf:read_conf:62 - 读取配置文件时出错: While reading from 'config.ini' [line 23]: section 'Temp' already exists
2024-09-14 13:54:18.123 | ERROR    | conf:write_conf:80 - 读取配置文件时出错: While reading from 'config.ini' [line 23]: section 'Temp' already exists
2024-09-14 13:54:18.132 | ERROR    | conf:read_conf:62 - 读取配置文件时出错: While reading from 'config.ini' [line 23]: section 'Temp' already exists
（仅提交了最新的一份崩溃日志）
```

### 应用版本

1.1.6

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

### 不要乱下载别人发的文件，特别是名字是fix.zip的文件。您是否遇见过这样的文件？

否

**Comment by RinLit-233-shiroko** [comment]
能否详细描述一下在首次打开软件后的行为（如：更改某个设置选项、使用了某些功能）

**Comment by Leozhu2010** [comment]
首次打开软件之后我导入了课表，然后开启了上下课弹窗提醒跟上课自动隐藏，随后关闭了自定义倒计时，刚设置完成的时候是正常工作的，但是到了下午启动的时候（不管啥时候设置的，早上也好晚上也好，但是晚上设置的第二天早上可以正常工作）就像上面那样了

**Comment by RinLit-233-shiroko** [comment]
把课程表配置文件发一下

**Comment by Leozhu2010** [comment]
课表我下周三去班上拷，config.ini在上面已经发了

**Comment by RinLit-233-shiroko** [comment]
目前暂没能复现，且照您的描述我觉得是课程表文件的设定出问题了

**Comment by Leozhu2010** [comment]
[config.txt](https://github.com/user-attachments/files/17005781/config.txt)
[新课表 - 1.json](https://github.com/user-attachments/files/17005782/-.1.json)
刚刚弄得克隆，选项跟学校生产环境一模一样，只是没配置课程，麻烦帮忙看看能不能复现

**Comment by Leozhu2010** [comment]
[新课表 - 1.json](https://github.com/user-attachments/files/17005788/-.1.json)
添加了课程的

**Comment by Leozhu2010** [comment]
我试试重新配置下课表然后周三复制过去吧

**Comment by Leozhu2010** [comment]
目前已无此问题
