### ISSUE TITLE
设置时差后 每日上/下午首个活动会重复提示活动开始 同时活动倒计时出错

### ISSUE THREAD

**Issue by Yersmagit** [RinLit-233-shiroko/Class-Widgets#47]
### 检查清单

- [X] 我已更新到最新版 ![GitHub Release](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_prereleases) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

设置时差偏移后，每日上/下午首个活动开始时不再重复弹出提示活动开始的弹窗，且活动倒计时的时间不会出现错误。

### 实际结果

设置 **时差偏移** 后，每日 **上/下午 首个** 活动开始前后，会分别在 **系统时间** 和 **计算后得到的时差校正时间** 到达设定时间时 **两次**弹出提示活动开始的弹窗，并且 **第一次弹出弹窗后** 到 **第二次弹出弹窗前** 所显示的 **活动倒计时** 也会出现错误。

### 重现步骤

1. 设定 **时差偏移**，正数负数皆可 **（以负数 -10 为例）** 。
   ![QQ_1726387422263](https://github.com/user-attachments/assets/6f11e6ac-5cad-41d7-b0d4-9e6e1e114ef8)
2. 设定上午课程起始时间（下午起始时间亦可）**（以 16:06 为例）** 。
   ![QQ_1726388492444](https://github.com/user-attachments/assets/a76bddc4-005f-4818-81a8-535556a52881)
3. 等待时间到达设定的起始时间。
4. 软件将会在 **系统时间** 和 **计算后得到的时差校正时间** 到达设定时间时 **两次** 弹出提示活动开始的弹窗；且 **第一次弹出弹窗后** 到 **第二次弹出弹窗前** 所显示的 **活动倒计时** 出现错误。
   比如在**示例**中，软件会在**系统时间**为 **16:05:50** 和 **16:06:00** 时 **先后两次弹出课程开始提醒**；系统时间 **16:05:50 - 16:06:00** 间，**活动倒计时** 时间出错 **（如下图所示）** 。
    ![image](https://github.com/user-attachments/assets/c22d26f6-ba68-485e-aec6-f7009f2e7849)

### 应用版本

1.1.6

### 操作系统版本

Windows 11 26120.1252

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

### 不要乱下载别人发的文件，特别是名字是fix.zip的文件。您是否遇见过这样的文件？

否

**Comment by RinLit-233-shiroko** [comment]
已成功修复此Bug！(～￣▽￣)～
将在下个版本更新
