### ISSUE TITLE
禁用上下课提醒后 活动开始前后或放学时无法自动切换程序主题色

### ISSUE THREAD

**Issue by Yersmagit** [RinLit-233-shiroko/Class-Widgets#48]
### 检查清单

- [X] 我已更新到最新版 ![GitHub Release](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_prereleases) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

禁用上下课提醒后，活动开始前后或放学时依然可以如启用了上下课提醒一样，正常自动切换程序主题色为橙色或绿色。

### 实际结果

禁用上下课提醒后，活动开始前后或放学时程序主题色不会自动切换。

### 重现步骤

1. 禁用上下课提醒。
2. 等待活动开始、结束或放学。
3. 程序没有如启用了上下课提醒一样，更改主题色为橙色或绿色。

### 应用版本

1.1.6

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

### 不要乱下载别人发的文件，特别是名字是fix.zip的文件。您是否遇见过这样的文件？

否

**Comment by xuanxuan1231** [comment]
出现同样的问题，简单复现方法：调系统时间

**Comment by RinLit-233-shiroko** [comment]
已修复ヾ(≧▽≦*)o
将在下个版本更新
