### ISSUE TITLE
v1.1.6中更新的新功能出现问题

### ISSUE THREAD

**Issue by XKaiZzzz** [RinLit-233-shiroko/Class-Widgets#51]
### 检查清单

- [X] 我已更新到最新版 ![GitHub Release](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_prereleases) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

小组件能在上课时正确地提醒当前课程。

### 实际结果

如下图，v1.1.6中更新的“‘上下课提醒弹窗’中添加课程信息”这一功能中**上课时提示的课程信息出现错误**，比如下一节课是阅读课（如图），但小组件在显示上课提示及课程时显示的本节课是“课间”，不是对应的课程，很影响使用，请修复此bug。
![Snipaste_2024-09-16_14-26-46](https://github.com/user-attachments/assets/40344600-b24e-4fdb-b07c-f30f380617c9)
![Snipaste_2024-09-16_14-28-12](https://github.com/user-attachments/assets/ec041d45-3d7f-4820-b6d2-fd8d304340d0)

### 重现步骤

1.首先，添加课程；
2.然后，等待上课小组件提示当前课程；
3.最后，错误出现。

### 堆栈跟踪（可选）

```shell
无
```

### 应用版本

1.1.6

### 操作系统版本

22635.3430

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

### 不要乱下载别人发的文件，特别是名字是fix.zip的文件。您是否遇见过这样的文件？

否

**Comment by RinLit-233-shiroko** [comment]
已修复ヾ(≧▽≦*)o
将在下个版本更新
