### ISSUE TITLE
如何向课表添加课程

### ISSUE THREAD

**Issue by yeying-xingchen** [RinLit-233-shiroko/Class-Widgets#58]
### 检查清单

- [X] 我已更新到最新版 ![GitHub Release](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_prereleases) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

保存课程信息

### 实际结果

点击后，查看课表，课表内未出现课程。

### 重现步骤

1.添加课程2.查看课表

### 应用版本

1.1.6

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

### 不要乱下载别人发的文件，特别是名字是fix.zip的文件。您是否遇见过这样的文件？

是

**Comment by RinLit-233-shiroko** [comment]
能详细描述你是如何添加课程的吗

### 步骤：
**1. 在”设置“->”时间线编辑“中编辑和保存时间线；
2. 在”课程表编辑“中添加课程，最后保存课程；
3. 完成。**
