### ISSUE TITLE
更改课程表文件名称并保存课程表更改后程序崩溃

### ISSUE THREAD

**Issue by Yersmagit** [RinLit-233-shiroko/Class-Widgets#59]
### 检查清单

- [X] 我已更新到最新版 ![GitHub Release](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_prereleases) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

更改课程表文件名称并保存课程表更改不会导致程序崩溃

### 实际结果

更改课程表文件名称并保存课程表更改后程序崩溃

### 重现步骤

1. 在高级选项中 选择课程表配置 后的文本框中输入任意文本。
   ![QQ_1726844907086](https://github.com/user-attachments/assets/13c51870-5dce-49f9-a291-574ff15df97b)
2. 在 时间线编辑/课程表编辑 页面中点击右下角保存。
3. 程序崩溃。

### 应用版本

1.1.6.5

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

### 不要乱下载别人发的文件，特别是名字是fix.zip的文件。您是否遇见过这样的文件？

否

**Comment by RinLit-233-shiroko** [comment]
已修复此Bug，将于下个版本更新
