### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by BuXSH** [RinLit-233-shiroko/Class-Widgets#6]
Traceback (most recent call last):
  File "main.py", line 455, in <module>
  File "conf.py", line 151, in add_shortcut
  File "<COMObject <unknown>>", line 2, in save
pywintypes.com_error: (-2147352567, '发生意外。', (0, 'WshShortcut.Save', '无法保存快捷方式“C:\\Users\\Hlhrdc\\Desktop\\ClassWidgets.lnk”。', None, 0, -2147024893), None)

**Comment by GEQfa** [comment]
我的也这样报错，但我双击设置却能打开应用

**Comment by ZianTT** [comment]
已经提交PR了 #3 ，但是好像被关闭了

**Comment by GEQfa** [comment]
> 已经提交PR了 #3 ，但是好像被关闭了

看到了，看作者会不会修复

**Comment by RinLit-233-shiroko** [comment]
ok，等我

**Comment by ZianTT** [comment]
都PR了就reopen一下然后merge不就好了（碎碎念

**Comment by RinLit-233-shiroko** [comment]
eee现在传好了，经测试已经没有崩溃 Bug

**Comment by BuXSH** [comment]
nb！！

**Comment by ZianTT** [comment]
> eee现在传好了，经测试已经没有崩溃 Bug

尊嘟假嘟你传的commit好像是空commit啊……
