### ISSUE TITLE
课程图标缺失

### ISSUE THREAD

**Issue by XKaiZzzz** [RinLit-233-shiroko/Class-Widgets#60]
### 检查清单

- [X] 我已更新到最新版 ![GitHub Release](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_prereleases) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

生物课程正确显示其对应的课程图标logo

### 实际结果

生物课程图标缺失（如图）
![Snipaste_2024-09-21_18-44-17](https://github.com/user-attachments/assets/a778654c-aa44-4d0e-8f60-8d31b1f3e9f2)

### 重现步骤

1.导入课程表，并设置生物课程；
2.等待生物课程开始；
3.看到生物课程没有图标。

### 应用版本

1.1.6.5

### 操作系统版本

19045.4894

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

### 不要乱下载别人发的文件，特别是名字是fix.zip的文件。您是否遇见过这样的文件？

否

**Comment by RinLit-233-shiroko** [comment]
请问资源文件确认过是完整的吗，其他课程有此问题吗

**Comment by RinLit-233-shiroko** [comment]
非常抱歉，我在一开始忘记画生物科的图标了，您暂时可以在网站上搜索相关的svg图标并命名为biology.svg
然后放到软件根目录img文件夹下即可（不过这居然到现在才有反馈）

**Comment by ZianTT** [comment]
> 非常抱歉，我在一开始忘记画生物科的图标了，您暂时可以在网站上搜索相关的svg图标并命名为biology.svg
> 然后放到软件根目录img文件夹下即可（不过这居然到现在才有反馈）

当时注意到了以为后面会更新就没反馈…😂
