### ISSUE TITLE
课程提示出现新问题

### ISSUE THREAD

**Issue by XKaiZzzz** [RinLit-233-shiroko/Class-Widgets#61]
### 检查清单

- [X] 我已更新到最新版 ![GitHub Release](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_prereleases) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

上次给作者反馈了由课间转为上课时候显示的错误，作者已将其修复，现在发现了与**该bug相似的另一bug**。即从“暂无课程”状态转到“上课”状态的时候对课程的提示会出现错误（如图），希望能修复此bug，正确显示上课的课程。
![Snipaste_2024-09-21_18-44-17](https://github.com/user-attachments/assets/af1ea828-09a2-42fd-a1ee-0eef97760a5a)
![Snipaste_2024-09-21_18-48-25](https://github.com/user-attachments/assets/09eda0d2-1a68-47d5-91f7-d7bf20ca2aab)
![Snipaste_2024-09-21_18-48-33](https://github.com/user-attachments/assets/d401fec3-1d5d-4dc6-b086-a60aeee3ad14)

### 实际结果

从“暂无课程”转为“上课”时课程信息不显示而显示“暂无课程”。

### 重现步骤

1.导入课程表；
2.设置时间线第一项为一节课程；
3.等待课程起始；
4.bug出现

### 应用版本

1.1.6.5

### 操作系统版本

19045.4894

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

### 不要乱下载别人发的文件，特别是名字是fix.zip的文件。您是否遇见过这样的文件？

否

**Comment by RinLit-233-shiroko** [comment]
啊哈哈，又有一个，好好好
马上修
