### ISSUE TITLE
在文件夹里将原本课程表json删除换入新课程表json，CW程序无法打开和运行

### ISSUE THREAD

**Issue by CXDark** [RinLit-233-shiroko/Class-Widgets#62]
### 检查清单

- [X] 我已更新到最新版 ![GitHub Release](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_prereleases) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

修复此bug，添加自动适配，检查文件等。

### 实际结果

程序无法运行

### 重现步骤

首先打开课程表路径下的文件夹config\schedule
替换其中的新课表 - 1.json 为 （任意名字）.json
然后保存后打开ClassWidgets.exe程序未报错，但无法打开。

### 应用版本

v1.1.6.5最新版

### 操作系统版本

Windows 10 22H2

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

### 不要乱下载别人发的文件，特别是名字是fix.zip的文件。您是否遇见过这样的文件？

否

**Comment by Yersmagit** [comment]
感觉跟 #59 有关

**Comment by CXDark** [comment]
经过实验，问题跟config目录下的config.ini疑似有关

**Comment by RinLit-233-shiroko** [comment]
请使用应用内自带的导入功能

**Comment by RinLit-233-shiroko** [comment]
不过自动适配可以加上（

**Comment by xuanxuan1231** [comment]
把config.ini里的json文件名调一下
