### ISSUE TITLE
最新版打不开

### ISSUE THREAD

**Issue by xuanxuan1231** [RinLit-233-shiroko/Class-Widgets#86]
### 检查清单

- [X] 我已更新到最新版 ![GitHub Release](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_prereleases) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

正常打开

### 实际结果

两个电脑都打不开，连日志都没有

### 重现步骤

打开 ClassWidgets.exe

### 应用版本

1.1.7-b1

### 操作系统版本

10.0.26100.1882, 10.0.22621.4037, 

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

### 不要乱下载别人发的文件，特别是名字是fix.zip的文件。您是否遇见过这样的文件？

否

**Comment by xuanxuan1231** [comment]
我知道没几个人会喜欢这种提出问题的方式，但是我能描述的只有这些……

**Comment by xuanxuan1231** [comment]
@RinLit-233-shiroko

**Comment by RinLit-233-shiroko** [comment]
啊这…又是不明bug，之前版本的打得开吗，我这里都正常

**Comment by xuanxuan1231** [comment]
> 啊这…又是不明bug，之前版本的打得开吗，我这里都正常

之前一直正常，只有这个版本不行

**Comment by xuanxuan1231** [comment]
@RinLit-233-shiroko 用源码试了一下，可能是天气功能的编码问题
把所有关于 weather 和 weather_db 的注释掉就能运行了
再把 widgets.json 中的 widgets-weather.ui 删掉就能显示了

**Comment by liubanlaobanzhang** [comment]
主要是……
甚至没有`log`输出……
（我甚至差点以为这个软件本身就没有log输出导致我还开了个废issue
（对不起Orz

**Comment by RinLit-233-shiroko** [comment]
> @RinLit-233-shiroko 用源码试了一下，可能是天气功能的编码问题 把所有关于 weather 和 weather_db 的注释掉就能运行了 再把 widgets.json 中的 widgets-weather.ui 删掉就能显示了

奇怪Bug+1，能详细提供您的解决方案吗

**Comment by xuanxuan1231** [comment]
> > @RinLit-233-shiroko 用源码试了一下，可能是天气功能的编码问题 把所有关于 weather 和 weather_db 的注释掉就能运行了 再把 widgets.json 中的 widgets-weather.ui 删掉就能显示了
> 
> 奇怪Bug+1，能详细提供您的解决方案吗

运行环境：Python 3.8(Microsoft Store) Windows 11
安装依赖后，运行 main.py 出现 `UnicodeDecodeError`，出现在 main.py 和 menu.py 的 `import weather_db as ...`，weather_db.py 中
将以上有关内容注释后，在 widgets.json 中删除 `widgets-weather.ui` 删掉
再运行就成功了

**Comment by liubanlaobanzhang** [comment]
![image](https://github.com/user-attachments/assets/006013c8-483a-4666-b373-49dba9235d24)
要不要考虑一下`weather_db.py`的编码问题……？
随便对`main.py`调试一下 结果`weather_db.py`报了个`GBK`的错误……

```
发生异常: UnicodeDecodeError
'gbk' codec can't decode byte 0xb4 in position 64: illegal multibyte sequence
  File "D:\gits\Class-Widgets\weather_db.py", line 5, in <module>
    weather_status = json.load(open('config/data/xiaomi_weather_status.json'))
  File "D:\gits\Class-Widgets\menu.py", line 25, in <module>
    import weather_db as wd
  File "D:\gits\Class-Widgets\main.py", line 19, in <module>
    import menu
UnicodeDecodeError: 'gbk' codec can't decode byte 0xb4 in position 64: illegal multibyte sequence
```

**Comment by xuanxuan1231** [comment]
@RinLit-233-shiroko um...把release的assets重新打包换一下？
