### ISSUE TITLE
添加更多天气源

### ISSUE THREAD

**Issue by Leozhu2010** [RinLit-233-shiroko/Class-Widgets#90]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_releases&style=flat-square&label=) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认我想要的功能还没有实现。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我认为我想要的功能是用户广泛需要的，插件不能替代的，且没有超出 **软件本来** 的开发目标，而非 **添加与课表及教学辅助无关的内容** 。
- [X] 我已知晓由于开发者时间精力有限，我提交的功能请求可能需要比较久的时间才能实现。

### 背景与动机

目前我已经将cw更新至最新1.1.7-b2版本，看到天气小组件我很开心
但是由于我们学校疑似通过希沃集控屏蔽了小米天气（可能是直接屏蔽*.mi.com）结果就是天气永远显示错误。

### 想要实现或优化的功能

能否添加更多天气源（比如墨迹、中央气象台、etc.）这样即使默认源不能用也能换源？

### 最后一步

- [X] 我认为上述的描述已经足以详细，以便开发人员理解您想要的功能。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

### 不要乱下载别人发的文件，特别是名字是fix.zip的文件。您是否遇见过这样的文件？

是

**Comment by RinLit-233-shiroko** [comment]
好的，会考虑的

**Comment by noxsk** [comment]
可以考虑使用彩云天气，公众号可以获取基于经纬度的网页地址，还有降水预警j

**Comment by RinLit-233-shiroko** [comment]
> 可以考虑使用彩云天气，公众号可以获取基于经纬度的网页地址，还有降水预警，网页抓取即可。

其实小米天气也是彩云的源（目前尝试上了和风天气

**Comment by xuanxuan1231** [comment]
高德加了 https://github.com/RinLit-233-shiroko/Class-Widgets/pull/96
