### ISSUE TITLE
高分辨率和 DPI 下左下角菜单显示不全

### ISSUE THREAD

**Issue by noxsk** [RinLit-233-shiroko/Class-Widgets#94]
### 检查清单

- [X] 我已更新到最新版 ![GitHub Release](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_prereleases) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

窗口化时正常显示左下角高级选项等

### 实际结果

我们学校是最新的 12 代低压平台，4k 300%（还是 350% 来着？），点进设置左下角必须全屏才能显示

### 重现步骤

1.打开设置

### 应用版本

1.1.7b2

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

### 不要乱下载别人发的文件，特别是名字是fix.zip的文件。您是否遇见过这样的文件？

否

**Comment by bywhite0** [comment]
其实是因为设置窗口默认大小太大导致的（
在较低分辨率(1366x768)和缩放100%情况下也能复现

**Comment by RinLit-233-shiroko** [comment]
好，目前已通过其他方法解决此问题，将在下个Beta版本更新

**Comment by Leozhu2010** [comment]
我们也是这个平台，也是这个问题（目前我通过调小hidpi比例暂时解决了问题）
